### ISSUE TITLE
instructions not clear

### ISSUE THREAD

**Issue by akylus** [akshayrajp/Geiger-Counter-Arduino#1]
Please add a proper description and a README file.

**Comment by akylus** [comment]
@akshayrajp

**Comment by akylus** [comment]
@akshayrajp

**Comment by akylus** [comment]
@akshayrajp

**Comment by akylus** [comment]
@akshayrajp

**Comment by akshayrajp** [comment]
Added a README. Will be extending it further as and when I improve this project.
